# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    # use docker container to build application
    docker:
      - image: cirrusci/flutter
    steps:
      # git clone repository from github to get the latest code version
      - checkout
      # run command after git pull. change
      - run: flutter doctor
      # build release version for android
      - run: flutter build apk --release
      # get build file from the path and store it in the cloud, so everyone can has access to it
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
